BOXDD_LAYOUT_VALUE( sizeof( b2Body ) )
BOXDD_LAYOUT_VALUE( sizeof( b2BodySim ) )
BOXDD_LAYOUT_VALUE( sizeof( b2BodyState ) )
BOXDD_LAYOUT_VALUE( sizeof( b2Shape ) )
BOXDD_LAYOUT_VALUE( sizeof( b2ChainShape ) )
BOXDD_LAYOUT_VALUE( sizeof( b2Contact ) )
BOXDD_LAYOUT_VALUE( sizeof( b2ContactSim ) )
BOXDD_LAYOUT_VALUE( sizeof( b2Joint ) )
BOXDD_LAYOUT_VALUE( sizeof( b2JointSim ) )
BOXDD_LAYOUT_VALUE( sizeof( b2Island ) )
BOXDD_LAYOUT_VALUE( sizeof( b2IslandSim ) )
BOXDD_LAYOUT_VALUE( sizeof( b2ContactLink ) )
BOXDD_LAYOUT_VALUE( sizeof( b2JointLink ) )
BOXDD_LAYOUT_VALUE( sizeof( b2Sensor ) )
BOXDD_LAYOUT_VALUE( sizeof( b2Visitor ) )
BOXDD_LAYOUT_VALUE( sizeof( b2SolverSet ) )
BOXDD_LAYOUT_VALUE( sizeof( b2GraphColor ) )
BOXDD_LAYOUT_VALUE( sizeof( b2DynamicTree ) )
BOXDD_LAYOUT_VALUE( sizeof( b2TreeNode ) )
BOXDD_LAYOUT_VALUE( sizeof( b2SetItem ) )
BOXDD_LAYOUT_VALUE( sizeof( b2IdPool ) )
BOXDD_LAYOUT_VALUE( sizeof( b2SurfaceMaterial ) )
BOXDD_LAYOUT_VALUE( B2_GRAPH_COLOR_COUNT )
BOXDD_LAYOUT_VALUE( b2_bodyTypeCount )
BOXDD_LAYOUT_VALUE( sizeof( void* ) )
