BOXDD_ABI_TYPE( b2Body )
BOXDD_ABI_FIELD( b2Body, userData )
BOXDD_ABI_FIELD( b2Body, setIndex )
BOXDD_ABI_FIELD( b2Body, localIndex )
BOXDD_ABI_FIELD( b2Body, headContactKey )
BOXDD_ABI_FIELD( b2Body, headShapeId )
BOXDD_ABI_FIELD( b2Body, headChainId )
BOXDD_ABI_FIELD( b2Body, headJointKey )
BOXDD_ABI_FIELD( b2Body, islandId )
BOXDD_ABI_FIELD( b2Body, id )
BOXDD_ABI_FIELD( b2Body, flags )
BOXDD_ABI_FIELD( b2Body, type )
BOXDD_ABI_FIELD( b2Body, generation )
BOXDD_ABI_FIELD( b2Body, name )

BOXDD_ABI_TYPE( b2BodySim )
BOXDD_ABI_FIELD( b2BodySim, transform )
BOXDD_ABI_FIELD( b2BodySim, center )
BOXDD_ABI_FIELD( b2BodySim, bodyId )
BOXDD_ABI_FIELD( b2BodySim, flags )
BOXDD_ABI_TYPE( b2BodyState )

BOXDD_ABI_TYPE( b2Shape )
BOXDD_ABI_FIELD( b2Shape, id )
BOXDD_ABI_FIELD( b2Shape, bodyId )
BOXDD_ABI_FIELD( b2Shape, prevShapeId )
BOXDD_ABI_FIELD( b2Shape, nextShapeId )
BOXDD_ABI_FIELD( b2Shape, sensorIndex )
BOXDD_ABI_FIELD( b2Shape, type )
BOXDD_ABI_FIELD( b2Shape, proxyKey )
BOXDD_ABI_FIELD( b2Shape, userData )
BOXDD_ABI_FIELD( b2Shape, generation )
BOXDD_ABI_FIELD( b2Shape, enableSensorEvents )
BOXDD_ABI_FIELD( b2Shape, enableContactEvents )
BOXDD_ABI_FIELD( b2Shape, enableCustomFiltering )
BOXDD_ABI_FIELD( b2Shape, enableHitEvents )
BOXDD_ABI_FIELD( b2Shape, enablePreSolveEvents )
BOXDD_ABI_FIELD( b2Shape, enlargedAABB )
BOXDD_ABI_TYPE( b2ChainShape )

BOXDD_ABI_TYPE( b2Contact )
BOXDD_ABI_FIELD( b2Contact, edges )
BOXDD_ABI_FIELD( b2Contact, islandId )
BOXDD_ABI_FIELD( b2Contact, setIndex )
BOXDD_ABI_FIELD( b2Contact, colorIndex )
BOXDD_ABI_FIELD( b2Contact, localIndex )
BOXDD_ABI_FIELD( b2Contact, shapeIdA )
BOXDD_ABI_FIELD( b2Contact, shapeIdB )
BOXDD_ABI_FIELD( b2Contact, contactId )
BOXDD_ABI_FIELD( b2Contact, flags )
BOXDD_ABI_FIELD( b2Contact, generation )
BOXDD_ABI_TYPE( b2ContactSim )
BOXDD_ABI_FIELD( b2ContactSim, contactId )
BOXDD_ABI_FIELD( b2ContactSim, shapeIdA )
BOXDD_ABI_FIELD( b2ContactSim, shapeIdB )
BOXDD_ABI_FIELD( b2ContactSim, manifold )
BOXDD_ABI_FIELD( b2ContactSim, simFlags )

BOXDD_ABI_TYPE( b2Joint )
BOXDD_ABI_FIELD( b2Joint, userData )
BOXDD_ABI_FIELD( b2Joint, setIndex )
BOXDD_ABI_FIELD( b2Joint, colorIndex )
BOXDD_ABI_FIELD( b2Joint, localIndex )
BOXDD_ABI_FIELD( b2Joint, edges )
BOXDD_ABI_FIELD( b2Joint, jointId )
BOXDD_ABI_FIELD( b2Joint, islandId )
BOXDD_ABI_FIELD( b2Joint, type )
BOXDD_ABI_FIELD( b2Joint, generation )
BOXDD_ABI_FIELD( b2Joint, collideConnected )
BOXDD_ABI_TYPE( b2JointSim )
BOXDD_ABI_FIELD( b2JointSim, jointId )
BOXDD_ABI_FIELD( b2JointSim, bodyIdA )
BOXDD_ABI_FIELD( b2JointSim, bodyIdB )
BOXDD_ABI_FIELD( b2JointSim, type )

BOXDD_ABI_TYPE( b2Island )
BOXDD_ABI_TYPE( b2IslandSim )
BOXDD_ABI_TYPE( b2ContactLink )
BOXDD_ABI_TYPE( b2JointLink )
BOXDD_ABI_TYPE( b2Sensor )
BOXDD_ABI_TYPE( b2Visitor )
BOXDD_ABI_TYPE( b2SolverSet )
BOXDD_ABI_TYPE( b2GraphColor )
BOXDD_ABI_TYPE( b2DynamicTree )
BOXDD_ABI_TYPE( b2TreeNode )
BOXDD_ABI_FIELD( b2TreeNode, aabb )
BOXDD_ABI_FIELD( b2TreeNode, categoryBits )
BOXDD_ABI_FIELD( b2TreeNode, children )
BOXDD_ABI_FIELD( b2TreeNode, parent )
BOXDD_ABI_FIELD( b2TreeNode, height )
BOXDD_ABI_FIELD( b2TreeNode, flags )
BOXDD_ABI_TYPE( b2SetItem )
BOXDD_ABI_TYPE( b2IdPool )
BOXDD_ABI_TYPE( b2SurfaceMaterial )
BOXDD_ABI_TYPE( b2Capacity )
BOXDD_ABI_VALUE( B2_GRAPH_COLOR_COUNT )
BOXDD_ABI_VALUE( b2_bodyTypeCount )
BOXDD_ABI_VALUE( sizeof( void* ) )
BOXDD_ABI_VALUE( BOXDD_SNAPSHOT_VERSION )
BOXDD_ABI_VALUE( B2_SECRET_COOKIE )
