[package]
name = "boxdd-provider-smoke"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false
description = "Browser-style provider smoke for boxdd"
license.workspace = true
repository.workspace = true
homepage.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = []
double-precision = ["boxdd/double-precision", "boxdd-sys/double-precision"]

[dependencies]
boxdd.workspace = true
boxdd-sys.workspace = true
