#!/usr/bin/env python3
"""
Update Box2D submodule and pregenerate bindings for boxdd-sys.

Why: docs.rs builds are offline and cannot fetch submodules. To guarantee
successful docs.rs builds, we pre-generate Rust bindings and vendor headers
via submodules locally before publishing.

Usage examples:
  # Update submodule and pregenerate bindings (debug profile)
  python tools/update_submodule_and_bindings.py

  # Release profile
  python tools/update_submodule_and_bindings.py --profile release

  # Skip submodule update (only regenerate bindings)
  python tools/update_submodule_and_bindings.py --submodules skip

Requirements:
  - git, cargo in PATH
  - Python 3.7+
"""

import argparse
import os
import subprocess
import sys
from pathlib import Path


def run(cmd, cwd=None, env=None, dry=False):
    print("$", " ".join(cmd))
    if dry:
        return 0
    try:
        subprocess.check_call(cmd, cwd=cwd, env=env)
        return 0
    except subprocess.CalledProcessError as e:
        print(f"Command failed (exit {e.returncode}): {' '.join(cmd)}", file=sys.stderr)
        return e.returncode


def find_bindings(target_dir: Path, profile: str, crate: str) -> Path | None:
    build_dir = target_dir / profile / "build"
    if not build_dir.exists():
        return None
    for p in build_dir.glob(f"{crate}-*/out/bindings.rs"):
        return p
    return None


def main() -> int:
    parser = argparse.ArgumentParser(description="Update submodule and pregenerate bindings for boxdd-sys")
    parser.add_argument("--profile", default="debug", choices=["debug", "release"], help="Cargo profile")
    parser.add_argument("--submodules", default="update", choices=["update", "skip"], help="Whether to update submodules")
    parser.add_argument("--wasm-target", default=None, choices=[None, "emscripten", "wasi"], help="Generate wasm-specific pregenerated bindings for the given target")
    parser.add_argument("--dry-run", action="store_true", help="Print commands only")
    args = parser.parse_args()

    repo_root = Path(__file__).resolve().parents[1]
    crate_root = repo_root / "boxdd-sys"
    submodule = crate_root / "third-party/box2d"

    if args.submodules == "update":
        print(f"Updating submodule: {submodule}")
        if not submodule.exists():
            rc = run(["git", "submodule", "update", "--init", "--recursive"], cwd=str(repo_root), dry=args.dry_run)
            if rc != 0:
                return rc
        else:
            rc = run(["git", "submodule", "update", "--init", "--recursive", "--remote"], cwd=str(repo_root), dry=args.dry_run)
            if rc != 0:
                return rc

    # Build to generate bindings, but skip native C build to speed up
    env = os.environ.copy()
    env["BOXDD_SYS_SKIP_CC"] = "1"
    profile_flag = ["--release"] if args.profile == "release" else []

    # Optionally build for wasm target to emit wasm-specific bindings
    if args.wasm_target is None:
        rc = run(["cargo", "build", "-p", "boxdd-sys", *profile_flag], cwd=str(repo_root), env=env, dry=args.dry_run)
        if rc != 0:
            return rc
        target_dir = Path(env.get("CARGO_TARGET_DIR", repo_root / "target"))
        bindings = find_bindings(target_dir, args.profile, "boxdd-sys")
        if bindings is None or not bindings.exists():
            print(f"Generated bindings.rs not found under {target_dir / args.profile / 'build'}", file=sys.stderr)
            return 3
        dest = crate_root / "src" / "bindings_pregenerated.rs"
        header = (
            "// AUTOGENERATED: pregenerated bindings for docs.rs/offline builds\n"
            "// To refresh, run tools/update_submodule_and_bindings.py\n\n"
        )
        if not args.dry_run:
            content = bindings.read_text(encoding="utf-8", errors="ignore")
            dest.write_text(header + content, encoding="utf-8")
        print(f"Updated pregenerated bindings: {dest}")
    else:
        # WASM generation path
        if args.wasm_target == "emscripten":
            emsdk = env.get("EMSDK") or os.environ.get("EMSDK")
            if not emsdk:
                print("EMSDK not set; cannot generate emscripten wasm bindings", file=sys.stderr)
                return 4
            sysroot = Path(emsdk) / "upstream" / "emscripten" / "cache" / "sysroot"
            extra = f"--sysroot={sysroot} -target wasm32-unknown-emscripten"
            env["BINDGEN_EXTRA_CLANG_ARGS_wasm32-unknown-emscripten"] = extra
            env["BINDGEN_EXTRA_CLANG_ARGS_wasm32_unknown_emscripten"] = extra
            target_triple = "wasm32-unknown-emscripten"
        else:
            wasi = env.get("WASI_SDK_PATH") or os.environ.get("WASI_SDK_PATH")
            if not wasi:
                print("WASI_SDK_PATH not set; cannot generate WASI wasm bindings", file=sys.stderr)
                return 4
            sysroot = Path(wasi) / "share" / "wasi-sysroot"
            extra = f"--sysroot={sysroot} -target wasm32-wasip1"
            env["BINDGEN_EXTRA_CLANG_ARGS_wasm32-wasip1"] = extra
            env["BINDGEN_EXTRA_CLANG_ARGS_wasm32_wasip1"] = extra
            target_triple = "wasm32-wasip1"

        rc = run(["cargo", "build", "-p", "boxdd-sys", *profile_flag, "--target", target_triple], cwd=str(repo_root), env=env, dry=args.dry_run)
        if rc != 0:
            return rc
        target_dir = Path(env.get("CARGO_TARGET_DIR", repo_root / "target")) / target_triple
        bindings = find_bindings(target_dir, args.profile, "boxdd-sys")
        if bindings is None or not bindings.exists():
            print(f"Generated wasm bindings.rs not found under {target_dir / args.profile / 'build'}", file=sys.stderr)
            return 3
        dest = crate_root / "src" / "wasm_bindings_pregenerated.rs"
        header = (
            "// AUTOGENERATED: wasm pregenerated bindings for offline builds\n"
            "// To refresh, run tools/update_submodule_and_bindings.py --wasm-target <emscripten|wasi>\n\n"
        )
        if not args.dry_run:
            content = bindings.read_text(encoding="utf-8", errors="ignore")
            dest.write_text(header + content, encoding="utf-8")
        print(f"Updated wasm pregenerated bindings: {dest}")

    print("Done.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
